/**
 * UI layout
 */
export const APP_RESIZE = 'APP_RESIZE';
export const SIDENAV_TOGGLE = 'SIDENAV_TOGGLE';
export const CHANGE_VIEW = 'CHANGE_VIEW';

/**
 * Customers
 */


/**
 * Order
 */

/**
 * Order Service
 */

/**
 * Service
 */
export const SERVICE_SCHEMA_INFO_PENDING = 'SERVICE_SCHEMA_INFO_PENDING';
export const SERVICE_SCHEMA_INFO_SUCCEEDED = 'SERVICE_SCHEMA_INFO_SUCCEEDED';
export const SERVICE_COLLECTION_READONLY_PENDING = 'SERVICE_COLLECTION_READONLY_PENDING';
export const SERVICE_READ_SUCCEEDED = 'SERVICE_READ_SUCCEEDED';
export const SERVICE_READ_FAILED = 'SERVICE_READ_FAILED';
export const SERVICE_READ_NEXT_PAGE = 'SERVICE_READ_NEXT_PAGE';
export const SERVICE_READ_PREV_PAGE = 'SERVICE_READ_PREV_PAGE';
